# _config.yml

# required, replace with your own information -----
title: Ifrah Khanyaree
author: Ifrah Khanyaree 
description: 
  Amalgamation of researcher, marketer, analytics enthusiast, reader, and runner.

baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

